name: Release APK

on:
  push:
    tags: ['v*']

permissions:
  contents: write

jobs:
  build:
    name: Create Release

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      working-directory: src/Android
      run: chmod +x gradlew
      
    - name: Build with Gradle
      working-directory: src/Android
      run: ./gradlew build

    - name: Version set
      uses: chkfung/android-version-actions@v1.2.3
      with:
        gradlePath: src/Android/app/build.gradle.kts
        versionName: ${{ github.ref_name }} 
        versionCode: ${{ github.run_number }}

    - name: Assemble release
      working-directory: src/Android
      run: ./gradlew assembleRelease
                
    - name: Sign APK
      uses: r0adkll/sign-android-release@v1.0.4
      id: sign_app
      with:
        releaseDirectory: src/Android/app/build/outputs/apk/release
        signingKeyBase64: ${{ secrets.ANDROID_KEYSTORE }}
        keyStorePassword: ${{ secrets.KEYSTORE_PASSWORD }}
        alias: ${{ secrets.KEY_ALIAS }}
        keyPassword: ${{ secrets.KEY_PASSWORD }}
      env:
          BUILD_TOOLS_VERSION: "34.0.0"

    - name: Rename APK file 
      run: | 
        mv src/Android/app/build/outputs/apk/release/app-release-unsigned-signed.apk \
        src/Android/app/build/outputs/apk/release/expiration-alert-${{ github.run_number }}.apk

    - name: Print folder tree
      uses: jaywcjlove/github-action-folder-tree@v1.2.0
      with:
        path: ./src/Android/app/build/outputs
        depth: 10

    - name: Uploading Artifact  
      uses: actions/upload-artifact@v4
      with:
        name: expiration-alert-${{ github.ref_name }}
        path: src/Android/app/build/outputs/apk/release/expiration-alert-${{ github.ref_name }}.apk
        if-no-files-found: error

    - name: Create Release
      uses: actions/create-release@v1
      id: create_release
      with:
        draft: false
        prerelease: false
        release_name: Release ${{ github.ref_name }}
        tag_name: ${{ github.ref_name }}
      env:
        GITHUB_TOKEN: ${{ github.token }}

    - name: Upload Android Artifact
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ github.token }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: src/Android/app/build/outputs/apk/release/expiration-alert-${{ github.run_number }}.apk
        asset_name: expiration-alert-${{ github.ref_name }}.apk
        asset_content_type: application/vnd.android.package-archive
